-- -----------------------------------------------------
-- Table `PII_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PII_DATA (
  ID VARCHAR(50) NOT NULL,
  ORG VARCHAR(100) NOT NULL,
  BUSINESS_NAME VARCHAR(1000) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  FNAME VARCHAR(255) NOT NULL,
  LNAME VARCHAR(255) NULL,
  TELEPHONE VARCHAR(45) NOT NULL,
  COUNTRY VARCHAR(100) NOT NULL,
  STATE VARCHAR(100) NULL,
  ACCEPT_POLICY TINYINT NULL DEFAULT 0,
  CREATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)ENGINE = INNODB;

CREATE UNIQUE INDEX IDX_PII_ORG_UNIQUE ON PII_DATA (ORG ASC);

-- -----------------------------------------------------
-- Table `ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ACCOUNT (
  ID VARCHAR(45) NOT NULL,
  ORG VARCHAR(100) NOT NULL,
  STATUS VARCHAR(45) NOT NULL DEFAULT 'IN_PROGRESS',
  OWNER_PII_REF VARCHAR(255) NULL,
  OWNER_USERNAME VARCHAR(255) NULL,
  OWNER_TEMP_PASSWORD VARCHAR(2048) NULL,
  CREATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  TENANT_ADMIN VARCHAR(45) NOT NULL,
  TENANT_ADMIN_PASS VARCHAR(2048) NOT NULL,
  PRIMARY KEY (ID))
ENGINE = INNODB;

CREATE UNIQUE INDEX IDX_ACC_ORG_UNIQUE ON ACCOUNT (ORG ASC);
