
-- -----------------------------------------------------
-- Table `REGISTRATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS REGISTRATION (
  REG_ID VARCHAR(50) NOT NULL,
  REG_ORG VARCHAR(100) NOT NULL,
  REG_BUSINESS_NAME VARCHAR(1000) NOT NULL,
  REG_STATUS VARCHAR(45) NOT NULL DEFAULT 'CREATED',
  REG_EMAIL VARCHAR(255) NOT NULL,
  REG_FNAME VARCHAR(255) NOT NULL,
  REG_LNAME VARCHAR(255) NULL,
  REG_USERNAME VARCHAR(255) NOT NULL,
  REG_PASSWORD VARCHAR(2048) NULL,
  REG_TELEPHONE VARCHAR(45) NOT NULL,
  REG_COUNTRY VARCHAR(100) NOT NULL,
  REG_STATE VARCHAR(100) NULL,
  REG_CREATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  REG_UPDATED_TIME DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REG_VERIFICATION_CODE VARCHAR(45) NULL,
  REG_ACCEPT_POLICY TINYINT NULL DEFAULT 0,
  PRIMARY KEY (REG_ID)
)ENGINE = INNODB;

CREATE UNIQUE INDEX IDX_REG_ORG_UNIQUE ON REGISTRATION (REG_ORG ASC);