/*
 * Copyright (c) 2024, WSO2 LLC. (http://www.wso2.org).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.healthcare.consentmgt.core;

public class SQLConstants {

    public static final int DEFAULT_SEARCH_LIMIT = 100;
    public static final int DEFAULT_SEARCH_OFFSET = 0;

    public static final String INSERT_SP_PURPOSE_MAPPING_SQL =
            "INSERT INTO CM_SVP_APP_PURPOSE_MAPPING (CONSUMER_KEY," + "PURPOSE_ID, PURPOSE_NAME, APP_NAME) values (?, ?, ?, ?)";

    public static final String UPDATE_SP_PURPOSE_MAPPING_SQL =
            "UPDATE CM_SVP_APP_PURPOSE_MAPPING SET CONSUMER_KEY = ?" + ",PURPOSE_ID = ?, PURPOSE_NAME = ?, APP_NAME = ? WHERE ID = ?";

    public static final String GET_ALL_PURPOSE_MAPPING_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME FROM CM_SVP_APP_PURPOSE_MAPPING ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String GET_SP_PURPOSE_MAPPING_BY_ID_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE ID = ?";

    public static final String GET_SP_PURPOSE_MAPPING_BY_CONSUMER_KEY_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE CONSUMER_KEY = ?";

    public static final String GET_SP_PURPOSE_MAPPING_BY_PURPOSE_ID_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE PURPOSE_ID = ?";

    public static final String GET_SP_PURPOSE_MAPPING_BY_APP_NAME_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE APP_NAME = ?";

    public static final String SEARCH_SP_PURPOSE_MAPPING_BY_PURPOSE_ID_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE PURPOSE_ID = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String SEARCH_SP_PURPOSE_MAPPING_BY_CONSUMER_KEY_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE CONSUMER_KEY = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String SEARCH_SP_PURPOSE_MAPPING_BY_APP_NAME_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE APP_NAME = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String SEARCH_SP_PURPOSE_MAPPING_BY_CONSUMER_KEY_PURPOSE_ID_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE CONSUMER_KEY = ? AND PURPOSE_ID = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String SEARCH_SP_PURPOSE_MAPPING_BY_APP_NAME_PURPOSE_ID_SQL =
            "SELECT ID, CONSUMER_KEY, PURPOSE_ID, PURPOSE_NAME, APP_NAME " + "FROM CM_SVP_APP_PURPOSE_MAPPING WHERE APP_NAME = ? AND PURPOSE_ID = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String GET_PURPOSE_NAME_FROM_ID = "SELECT NAME FROM CM_PURPOSE WHERE ID = ?";

    public static final String GET_APP_NAME_FROM_CONSUMER_KEY = "SELECT APP_NAME FROM IDN_OAUTH_CONSUMER_APPS WHERE CONSUMER_KEY = ?";

    public static final String DELETE_SP_PURPOSE_MAPPING_BY_ID_SQL =
            "DELETE FROM CM_SVP_APP_PURPOSE_MAPPING WHERE ID = ?";

    public static final String GET_ALL_APPLICATION_KEYS =
            "SELECT DISTINCT CONSUMER_KEY, APP_NAME FROM CM_SVP_APP_PURPOSE_MAPPING ORDER BY CONSUMER_KEY ASC LIMIT ? OFFSET ?";

    public static final String GET_ALL_PURPOSES_FOR_APP =
            "SELECT PURPOSE_ID, PURPOSE_NAME FROM CM_SVP_APP_PURPOSE_MAPPING WHERE CONSUMER_KEY = ?";

    public static final String INSERT_PII_CATEGORY_MAPPING_SQL =
            "INSERT INTO CM_OH_PII_CATEGORY_MAPPING (PII_CATEGORY_ID," + "TYPE) values (?, ?)";

    public static final String GET_ALL_PII_CATEGORY_MAPPINGS =
            "SELECT ID, PII_CATEGORY_ID, TYPE FROM CM_OH_PII_CATEGORY_MAPPING ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String GET_ALL_PII_CATEGORY_MAPPINGS_FROM_CATEGORY_ID =
            "SELECT ID, PII_CATEGORY_ID, TYPE FROM CM_OH_PII_CATEGORY_MAPPING WHERE PII_CATEGORY_ID = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String GET_ALL_PII_CATEGORY_MAPPINGS_BY_TYPE =
            "SELECT ID, PII_CATEGORY_ID, TYPE FROM CM_OH_PII_CATEGORY_MAPPING WHERE TYPE = ? ORDER BY ID ASC LIMIT ? OFFSET ?";

    public static final String GET_ALL_PII_CATEGORY_MAPPINGS_BY_ID =
            "SELECT ID, PII_CATEGORY_ID, TYPE FROM CM_OH_PII_CATEGORY_MAPPING WHERE ID = ?";
}
