-- CONSENT-MGT Tables --

CREATE TABLE CM_SVP_APP_PURPOSE_MAPPING (
  ID           INTEGER(11)  NOT NULL AUTO_INCREMENT,
  CONSUMER_KEY VARCHAR(255) NOT NULL,
  PURPOSE_ID   INTEGER(11)  NOT NULL,
  PURPOSE_NAME VARCHAR(255) DEFAULT NULL,
  APP_NAME     VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY CM_SVP_APP_PURPOSE_MAPPING_ibfk_1 (CONSUMER_KEY),
  KEY CM_SVP_APP_PURPOSE_MAPPING_ibfk_2 (PURPOSE_ID),
  CONSTRAINT CM_SVP_APP_PURPOSE_MAPPING_ibfk_1 FOREIGN KEY (CONSUMER_KEY) REFERENCES IDN_OAUTH_CONSUMER_APPS (CONSUMER_KEY),
  CONSTRAINT CM_SVP_APP_PURPOSE_MAPPING_ibfk_2 FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE CM_OH_PII_CATEGORY_MAPPING (
  ID              INTEGER(11)  NOT NULL AUTO_INCREMENT,
  TYPE            VARCHAR(255) NOT NULL,
  PII_CATEGORY_ID INTEGER(11)  NOT NULL,
  PRIMARY KEY (ID),
  KEY CM_OH_PII_CATEGORY_MAPPING_ibfk_1 (PII_CATEGORY_ID),
  CONSTRAINT CM_OH_PII_CATEGORY_MAPPING_ibfk_1 FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- FHIR Private Key JWT Auth Table --

CREATE TABLE IF NOT EXISTS OH_IDN_SMART_BE_AUTH (
  JWT_ID VARCHAR(255),
  ISSUER VARCHAR(255),
  EXP_TIME TIMESTAMP NOT NULL ,
  PRIMARY KEY (JWT_ID, ISSUER)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
